# Generated by Django 4.2.5 on 2023-09-23 07:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextra',
            name='biografia',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
