# Generated by Django 4.2.5 on 2023-09-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PelucheAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=30)),
                ('altura', models.FloatField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
